bind_addr = ":8080"
log_level = "debug"
database_url = "postgres://cpkaewifcnydgj:c26b9ba150a0fa8138177d70dc867e5526e87eb766a6a6223d48a2e554307c4e@ec2-35-173-94-156.compute-1.amazonaws.com:5432/d4f3f59p6qbv5e"
session_key = "C6HZdNZnvcNzQPubAc1zCQQTrwhTo3jqJ9LQziezrAIX5dn9bDUWGPuESCxYYfGogZWTDoPVXBt62ZvwsZdC5lpOutJoR9MdsvKydMjsQXfyfYwkgaXZYx5puv9jYXyL43Vzirh9JHr0f3GMd8xHjLKyr9XNWQeWsSMA6sGy0AztAfHVnbKK2sH4Fi7KV1tI1LaEZX9vyJZec4lfusQRXG19zZQ3"