bind_addr = ":8080"
log_level = "debug"
session_key = "C6HZdNZnvcNzQPubAc1zCQQTrwhTo3jqJ9LQziezrAIX5dn9bDUWGPuESCxYYfGogZWTDoPVXBt62ZvwsZdC5lpOutJoR9MdsvKydMjsQXfyfYwkgaXZYx5puv9jYXyL43Vzirh9JHr0f3GMd8xHjLKyr9XNWQeWsSMA6sGy0AztAfHVnbKK2sH4Fi7KV1tI1LaEZX9vyJZec4lfusQRXG19zZQ3"